//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "activos_equipos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_equipo: i32,
    pub codigo_equipo: String,
    pub nombre_equipo: String,
    pub descripcion: Option<String>,
    pub categoria: Option<String>,
    pub marca: Option<String>,
    pub modelo: Option<String>,
    pub numero_serie: Option<String>,
    pub ubicacion: Option<String>,
    pub area_responsable: Option<String>,
    pub estado: Option<String>,
    pub fecha_adquisicion: Option<Date>,
    pub vida_util_meses: Option<i32>,
    pub fecha_fin_vida_util: Option<Date>,
    pub valor_compra: Option<Decimal>,
    pub proveedor_id: Option<i32>,
    pub responsable_id: Option<i32>,
    pub observaciones: Option<String>,
    pub imagen_url: Option<String>,
    pub tipo_activo: Option<String>,
    pub anio: Option<i32>,
    pub color: Option<String>,
    pub numero_motor: Option<String>,
    pub numero_chasis: Option<String>,
    pub manual_pdf: Option<String>,
    pub cantidad: Option<i32>,
    pub ubicacion_detallada: Option<String>,
    pub fecha_instalacion: Option<Date>,
    pub fecha_baja: Option<Date>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::historial_repuestos::Entity")]
    HistorialRepuestos,
    #[sea_orm(has_many = "super::mantenimiento_calendario::Entity")]
    MantenimientoCalendario,
    #[sea_orm(has_many = "super::mantenimiento_historial::Entity")]
    MantenimientoHistorial,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::ProveedorId",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Proveedores,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::ResponsableId",
        to = "super::usuarios::Column::IdUsuario",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::historial_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistorialRepuestos.def()
    }
}

impl Related<super::mantenimiento_calendario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoCalendario.def()
    }
}

impl Related<super::mantenimiento_historial::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoHistorial.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
