//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activos_repuestos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_repuesto: i32,
    pub codigo_repuesto: String,
    pub nombre_repuesto: String,
    pub descripcion: Option<String>,
    pub marca: Option<String>,
    pub modelo: Option<String>,
    pub tipo_repuesto: Option<String>,
    pub stock_actual: Option<i32>,
    pub stock_minimo: Option<i32>,
    pub unidad_medida: Option<String>,
    pub costo_unitario: Option<Decimal>,
    pub ubicacion_almacen: Option<String>,
    pub proveedor_id: Option<i32>,
    pub estado: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::historial_repuestos::Entity")]
    HistorialRepuestos,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::ProveedorId",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Proveedores,
}

impl Related<super::historial_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistorialRepuestos.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
