//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "activos_documentos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub activo_id: i32,
    pub nombre_archivo: String,
    pub url_archivo: String,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_equipos::Entity",
        from = "Column::ActivoId",
        to = "super::activos_equipos::Column::IdEquipo",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ActivosEquipos,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
