//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auditoria_acciones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_auditoria: i32,
    pub usuario_id: Option<i32>,
    pub accion: Option<String>,
    pub tabla_afectada: Option<String>,
    pub registro_id: Option<i32>,
    pub fecha: Option<DateTimeWithTimeZone>,
    pub ip_origen: Option<String>,
    pub detalle: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::UsuarioId",
        to = "super::usuarios::Column::IdUsuario",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
