//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bodega_ubicaciones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bodega_id: i32,
    pub nombre: String,
    pub descripcion: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activos_repuestos::Entity")]
    ActivosRepuestos,
    #[sea_orm(
        belongs_to = "super::bodegas::Entity",
        from = "Column::BodegaId",
        to = "super::bodegas::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Bodegas,
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::bodegas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bodegas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
