//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bodegas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub nombre: String,
    pub ubicacion: Option<String>,
    pub descripcion: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activos_repuestos::Entity")]
    ActivosRepuestos,
    #[sea_orm(has_many = "super::bodega_ubicaciones::Entity")]
    BodegaUbicaciones,
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::bodega_ubicaciones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BodegaUbicaciones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
