//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "componentes_estandar")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nombre: String,
    pub categoria: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activo_componentes::Entity")]
    ActivoComponentes,
}

impl Related<super::activo_componentes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivoComponentes.def()
    }
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        super::activo_componentes::Relation::ActivosEquipos.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::activo_componentes::Relation::ComponentesEstandar.def().rev())
    }
}


impl ActiveModelBehavior for ActiveModel {}
