//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compras_solicitud_detalle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub solicitud_id: i32,
    pub repuesto_id: Option<i32>,
    pub descripcion_item: Option<String>,
    pub cantidad: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::compras_solicitudes::Entity",
        from = "Column::SolicitudId",
        to = "super::compras_solicitudes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ComprasSolicitudes,
}

impl Related<super::compras_solicitudes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComprasSolicitudes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
