//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "compras_cotizaciones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub proveedor_id: i32,
    pub fecha_solicitud: Date,
    pub codigo: String,
    pub estado: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub observaciones: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::compras_cotizacion_detalle::Entity")]
    ComprasCotizacionDetalle,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::ProveedorId",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Proveedores,
}

impl Related<super::compras_cotizacion_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComprasCotizacionDetalle.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
