//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "compras_solicitudes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub solicitante_id: i32,
    pub fecha_solicitud: Date,
    #[sea_orm(column_type = "Text")]
    pub motivo: String,
    pub estado: String,
    pub prioridad: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::compras_solicitud_detalle::Entity")]
    ComprasSolicitudDetalle,
}

impl Related<super::compras_solicitud_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComprasSolicitudDetalle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
