//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "facturas_compras_detalle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_factura: i32,
    pub id_repuesto: i32,
    pub id_detalle_oc: Option<i32>,
    pub cantidad: i32,
    pub costo_unitario: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::IdRepuesto",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ActivosRepuestos,
    #[sea_orm(
        belongs_to = "super::facturas_compras::Entity",
        from = "Column::IdFactura",
        to = "super::facturas_compras::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FacturasCompras,
    #[sea_orm(
        belongs_to = "super::orden_compra_detalle::Entity",
        from = "Column::IdDetalleOc",
        to = "super::orden_compra_detalle::Column::IdDetalle",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    OrdenCompraDetalle,
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::facturas_compras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasCompras.def()
    }
}

impl Related<super::orden_compra_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenCompraDetalle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
