//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "facturas_compras")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_orden_compra: Option<i32>,
    pub id_proveedor: i32,
    pub numero_factura: String,
    pub fecha_emision: Date,
    pub fecha_recepcion: Option<Date>,
    pub subtotal: Decimal,
    pub impuestos: Decimal,
    pub total: Decimal,
    pub estado: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notas: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::facturas_compras_detalle::Entity")]
    FacturasComprasDetalle,
    #[sea_orm(
        belongs_to = "super::orden_compra_repuesto::Entity",
        from = "Column::IdOrdenCompra",
        to = "super::orden_compra_repuesto::Column::IdOrdenCompra",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    OrdenCompraRepuesto,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::IdProveedor",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Proveedores,
}

impl Related<super::facturas_compras_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasComprasDetalle.def()
    }
}

impl Related<super::orden_compra_repuesto::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenCompraRepuesto.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
