//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "feriados_pa")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fecha: Date,
    pub descripcion: String,
    pub es_fijo: bool,
    pub estado: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
