//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "historial_repuestos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_historial_repuesto: i32,
    pub repuesto_id: i32,
    pub equipo_id: Option<i32>,
    pub mantenimiento_id: Option<i32>,
    pub cantidad_utilizada: Option<i32>,
    pub fecha_uso: Option<Date>,
    pub tecnico_responsable: Option<String>,
    pub motivo: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub orden_trabajo_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_equipos::Entity",
        from = "Column::EquipoId",
        to = "super::activos_equipos::Column::IdEquipo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ActivosEquipos,
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::RepuestoId",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ActivosRepuestos,
    #[sea_orm(
        belongs_to = "super::mantenimiento_historial::Entity",
        from = "Column::MantenimientoId",
        to = "super::mantenimiento_historial::Column::IdMantenimiento",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MantenimientoHistorial,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::mantenimiento_historial::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoHistorial.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
