//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventario_movimientos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub repuesto_id: i32,
    pub tipo: String,
    pub cantidad: i32,
    pub referencia_id: Option<i32>,
    pub fecha: Option<DateTimeWithTimeZone>,
    pub usuario_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
