//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mantenimiento_tareas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nombre: String,
    pub descripcion: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mantenimiento_calendario::Entity")]
    MantenimientoCalendario,
    #[sea_orm(has_many = "super::mantenimiento_historial::Entity")]
    MantenimientoHistorial,
}

impl Related<super::mantenimiento_calendario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoCalendario.def()
    }
}

impl Related<super::mantenimiento_historial::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoHistorial.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
