//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mantenimiento_repuestos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mantenimiento_id: i32,
    pub repuesto_id: i32,
    pub cantidad_estimada: Decimal,
    pub costo_estimado: Decimal,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::RepuestoId",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ActivosRepuestos,
    #[sea_orm(
        belongs_to = "super::mantenimiento_calendario::Entity",
        from = "Column::MantenimientoId",
        to = "super::mantenimiento_calendario::Column::IdMantenimientoCalendario",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MantenimientoCalendario,
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::mantenimiento_calendario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoCalendario.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
