//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mantenimiento_calendario")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_mantenimiento_calendario: i32,
    pub equipo_id: i32,
    pub tipo_mantenimiento_id: i32,
    pub frecuencia: Option<String>,
    pub intervalo_valor: Option<i32>,
    pub fecha_programada: Option<Date>,
    pub fecha_ultima_ejecucion: Option<Date>,
    pub proxima_fecha: Option<Date>,
    pub responsable_id: Option<i32>,
    pub estado: Option<String>,
    pub observaciones: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub codigo_mantenimiento: Option<String>,
    pub prioridad: Option<String>,
    pub costo_estimado: Option<Decimal>,
    pub dias_anticipacion: Option<i32>,
    pub proveedor_id: Option<i32>,
    pub tecnico_id: Option<i32>,
    pub tarea_tipo_id: Option<i32>,
    pub recurrente: bool,
    pub responsable_interno_email: Option<String>,
    pub orden_trabajo_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_equipos::Entity",
        from = "Column::EquipoId",
        to = "super::activos_equipos::Column::IdEquipo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ActivosEquipos,
    #[sea_orm(has_many = "super::mantenimiento_historial::Entity")]
    MantenimientoHistorial,
    #[sea_orm(has_many = "super::mantenimiento_repuestos::Entity")]
    MantenimientoRepuestos,
    #[sea_orm(
        belongs_to = "super::mantenimiento_tareas::Entity",
        from = "Column::TareaTipoId",
        to = "super::mantenimiento_tareas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MantenimientoTareas,
    #[sea_orm(
        belongs_to = "super::mantenimiento_tipo::Entity",
        from = "Column::TipoMantenimientoId",
        to = "super::mantenimiento_tipo::Column::IdTipoMantenimiento",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MantenimientoTipo,
    #[sea_orm(
        belongs_to = "super::orden_trabajo::Entity",
        from = "Column::OrdenTrabajoId",
        to = "super::orden_trabajo::Column::IdOt",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    OrdenTrabajo,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::ResponsableId",
        to = "super::usuarios::Column::IdUsuario",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl Related<super::mantenimiento_historial::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoHistorial.def()
    }
}

impl Related<super::mantenimiento_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoRepuestos.def()
    }
}

impl Related<super::mantenimiento_tareas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoTareas.def()
    }
}

impl Related<super::mantenimiento_tipo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoTipo.def()
    }
}

impl Related<super::orden_trabajo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenTrabajo.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
