//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "orden_compra_detalle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_detalle: i32,
    pub id_orden_compra: i32,
    pub id_repuesto: i32,
    pub cantidad: i32,
    pub costo_unitario: Option<Decimal>,
    pub cantidad_recibida: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::facturas_compras_detalle::Entity")]
    FacturasComprasDetalle,
}

impl Related<super::facturas_compras_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasComprasDetalle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
