//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orden_trabajo_comentarios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_comentario: i32,
    pub ot_id: i32,
    pub usuario_id: i32,
    #[sea_orm(column_type = "Text")]
    pub comentario: String,
    pub fecha_hora: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orden_trabajo::Entity",
        from = "Column::OtId",
        to = "super::orden_trabajo::Column::IdOt",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OrdenTrabajo,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::UsuarioId",
        to = "super::usuarios::Column::IdUsuario",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::orden_trabajo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenTrabajo.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
