//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orden_compra_detalle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_detalle: i32,
    pub id_orden_compra: i32,
    pub id_repuesto: i32,
    pub cantidad: i32,
    pub costo_unitario: Option<Decimal>,
    pub cantidad_recibida: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::facturas_compras_detalle::Entity")]
    FacturasComprasDetalle,
    #[sea_orm(
        belongs_to = "super::orden_compra_repuesto::Entity",
        from = "Column::IdOrdenCompra",
        to = "super::orden_compra_repuesto::Column::IdOrdenCompra",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OrdenCompraRepuesto,
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::IdRepuesto",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    ActivosRepuestos,
}

impl Related<super::orden_compra_repuesto::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenCompraRepuesto.def()
    }
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::facturas_compras_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasComprasDetalle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
