//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orden_trabajo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_ot: i32,
    pub id_calendario: Option<i32>,
    pub id_activo: i32,
    pub id_tipo_mantenimiento: Option<i32>,
    pub id_tecnico: Option<i32>,
    pub id_proveedor: Option<i32>,
    pub fecha_inicio_real: Option<DateTime>,
    pub fecha_fin_real: Option<DateTime>,
    pub estado: Option<String>,
    pub prioridad: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub observaciones: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub codigo_ot: Option<String>,
    pub costo_estimado: Option<Decimal>,
    pub terminos_pago: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mantenimiento_calendario::Entity",
        from = "Column::IdCalendario",
        to = "super::mantenimiento_calendario::Column::IdMantenimientoCalendario",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    MantenimientoCalendario,
    #[sea_orm(
        belongs_to = "super::activos_equipos::Entity",
        from = "Column::IdActivo",
        to = "super::activos_equipos::Column::IdEquipo",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ActivosEquipos,
}

impl Related<super::mantenimiento_calendario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoCalendario.def()
    }
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
