//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orden_compra_repuesto")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_orden_compra: i32,
    pub id_ot: Option<i32>,
    pub id_proveedor: Option<i32>,
    pub fecha_solicitud: Option<Date>,
    pub estado: Option<String>,
    pub total_estimado: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub codigo_compra: Option<String>,
    pub solicitud_id: Option<i32>,
    pub estado_recepcion: Option<String>,
    pub fecha_entrega: Option<Date>,
    pub terminos_pago: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notas: Option<String>,
    pub impuestos: Option<Decimal>,
    pub subtotal: Option<Decimal>,
    pub total: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::facturas_compras::Entity")]
    FacturasCompras,
    #[sea_orm(has_many = "super::orden_compra_detalle::Entity")]
    OrdenCompraDetalle,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::IdProveedor",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Proveedores,
}

impl Related<super::facturas_compras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasCompras.def()
    }
}

impl Related<super::orden_compra_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenCompraDetalle.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
