//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orden_compra_repuesto")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_orden_compra: i32,
    pub id_ot: Option<i32>,
    pub id_proveedor: Option<i32>,
    pub fecha_solicitud: Option<Date>,
    pub estado: Option<String>,
    pub total_estimado: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub codigo_compra: Option<String>,
    pub solicitud_id: Option<i32>,
    pub estado_recepcion: Option<String>,
    pub fecha_entrega: Option<Date>,
    pub terminos_pago: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notas: Option<String>,
    pub impuestos: Option<Decimal>,
    pub subtotal: Option<Decimal>,
    pub total: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
