//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permisos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_permiso: i32,
    pub codigo_permiso: String,
    pub descripcion: Option<String>,
    pub modulo: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rol_permisos::Entity")]
    RolPermisos,
}

impl Related<super::rol_permisos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolPermisos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
