//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::activos_repuestos::Entity as ActivosRepuestos;
pub use super::compras_solicitud_detalle::Entity as ComprasSolicitudDetalle;
pub use super::compras_solicitudes::Entity as ComprasSolicitudes;
pub use super::orden_compra_detalle::Entity as OrdenCompraDetalle;
pub use super::orden_compra_repuesto::Entity as OrdenCompraRepuesto;
pub use super::proveedores::Entity as Proveedores;
