//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "proveedores")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_proveedor: i32,
    pub nombre_proveedor: String,
    pub tipo_proveedor: Option<String>,
    pub contacto_nombre: Option<String>,
    pub telefono: Option<String>,
    pub email: Option<String>,
    pub direccion: Option<String>,
    pub pais: Option<String>,
    pub estado: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub codigo_proveedor: Option<String>,
    pub rut_o_ruc: Option<String>,
    pub ciudad: Option<String>,
    pub sitio_web: Option<String>,
    pub metodos_pago_aceptados: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub observaciones: Option<String>,
    pub dv: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activos_equipos::Entity")]
    ActivosEquipos,
    #[sea_orm(has_many = "super::activos_repuestos::Entity")]
    ActivosRepuestos,
    #[sea_orm(has_many = "super::tecnicos::Entity")]
    Tecnicos,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::tecnicos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tecnicos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
