//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "reportes_programados")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nombre: String,
    pub tipo_reporte: String,
    pub frecuencia: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub filtros: Option<Json>,
    pub ultimo_envio: Option<DateTimeWithTimeZone>,
    pub proximo_envio: Option<DateTimeWithTimeZone>,
    pub destinatarios: Option<String>,
    pub activo: Option<bool>,
    pub fecha_inicio: Date,
    pub fecha_fin: Option<Date>,
    pub hora_ejecucion: Time,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
