//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "repuestos_equipos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub repuesto_id: i32,
    pub equipo_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_equipos::Entity",
        from = "Column::EquipoId",
        to = "super::activos_equipos::Column::IdEquipo",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ActivosEquipos,
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::RepuestoId",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ActivosRepuestos,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
