//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_rol: i32,
    pub nombre_rol: String,
    pub descripcion: Option<String>,
    pub nivel: Option<i32>,
    pub estado: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rol_permisos::Entity")]
    RolPermisos,
    #[sea_orm(has_many = "super::usuario_roles::Entity")]
    UsuarioRoles,
}

impl Related<super::rol_permisos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolPermisos.def()
    }
}

impl Related<super::usuario_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsuarioRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
