//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "usuario_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_usuario_rol: i32,
    pub usuario_id: i32,
    pub rol_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RolId",
        to = "super::roles::Column::IdRol",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Roles,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::UsuarioId",
        to = "super::usuarios::Column::IdUsuario",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
