//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "usuarios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_usuario: i32,
    pub nombre: String,
    pub apellido: String,
    pub email: String,
    pub usuario: String,
    pub password_hash: String,
    pub telefono: Option<String>,
    pub cargo: Option<String>,
    pub empresa_id: Option<i32>,
    pub estado: Option<String>,
    pub ultimo_login: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub codigo_usuario: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activos_equipos::Entity")]
    ActivosEquipos,
    #[sea_orm(has_many = "super::auditoria_acciones::Entity")]
    AuditoriaAcciones,
    #[sea_orm(
        belongs_to = "super::empresas::Entity",
        from = "Column::EmpresaId",
        to = "super::empresas::Column::IdEmpresa",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Empresas,
    #[sea_orm(has_many = "super::mantenimiento_calendario::Entity")]
    MantenimientoCalendario,
    #[sea_orm(has_many = "super::orden_trabajo_comentarios::Entity")]
    OrdenTrabajoComentarios,
    #[sea_orm(has_many = "super::usuario_roles::Entity")]
    UsuarioRoles,
}

impl Related<super::activos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosEquipos.def()
    }
}

impl Related<super::auditoria_acciones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditoriaAcciones.def()
    }
}

impl Related<super::empresas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Empresas.def()
    }
}

impl Related<super::mantenimiento_calendario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoCalendario.def()
    }
}

impl Related<super::orden_trabajo_comentarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrdenTrabajoComentarios.def()
    }
}

impl Related<super::usuario_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsuarioRoles.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::usuario_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::usuario_roles::Relation::Usuarios.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
