//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "activos_repuestos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_repuesto: i32,
    pub codigo_repuesto: String,
    pub nombre_repuesto: String,
    pub descripcion: Option<String>,
    pub marca: Option<String>,
    pub modelo: Option<String>,
    pub tipo_repuesto: Option<String>,
    pub stock_actual: Option<i32>,
    pub stock_minimo: Option<i32>,
    pub unidad_medida: Option<String>,
    pub costo_unitario: Option<Decimal>,
    pub ubicacion_almacen: Option<String>,
    pub proveedor_id: Option<i32>,
    pub estado: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub imagen: Option<String>,
    pub ubicacion_fisica_exacta: Option<String>,
    pub fecha_ultima_compra: Option<Date>,
    pub fecha_instalacion: Option<Date>,
    pub fecha_vencimiento: Option<Date>,
    pub compatibilidad_modelos: Option<String>,
    pub vida_util_estimada: Option<String>,
    pub stock_reservado: i32,
    pub bodega_id: Option<i32>,
    pub ubicacion_bodega_id: Option<i32>,
    pub sku: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bodega_ubicaciones::Entity",
        from = "Column::UbicacionBodegaId",
        to = "super::bodega_ubicaciones::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    BodegaUbicaciones,
    #[sea_orm(
        belongs_to = "super::bodegas::Entity",
        from = "Column::BodegaId",
        to = "super::bodegas::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Bodegas,
    #[sea_orm(has_many = "super::compras_cotizacion_detalle::Entity")]
    ComprasCotizacionDetalle,
    #[sea_orm(has_many = "super::facturas_compras_detalle::Entity")]
    FacturasComprasDetalle,
    #[sea_orm(has_many = "super::historial_repuestos::Entity")]
    HistorialRepuestos,
    #[sea_orm(has_many = "super::mantenimiento_repuestos::Entity")]
    MantenimientoRepuestos,
    #[sea_orm(
        belongs_to = "super::proveedores::Entity",
        from = "Column::ProveedorId",
        to = "super::proveedores::Column::IdProveedor",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Proveedores,
    #[sea_orm(has_many = "super::repuestos_equipos::Entity")]
    RepuestosEquipos,
}

impl Related<super::bodega_ubicaciones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BodegaUbicaciones.def()
    }
}

impl Related<super::bodegas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bodegas.def()
    }
}

impl Related<super::compras_cotizacion_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComprasCotizacionDetalle.def()
    }
}

impl Related<super::facturas_compras_detalle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FacturasComprasDetalle.def()
    }
}

impl Related<super::historial_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistorialRepuestos.def()
    }
}

impl Related<super::mantenimiento_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MantenimientoRepuestos.def()
    }
}

impl Related<super::proveedores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proveedores.def()
    }
}

impl Related<super::repuestos_equipos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RepuestosEquipos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
