//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "compras_cotizacion_detalle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cotizacion_id: i32,
    pub repuesto_id: i32,
    pub cantidad: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activos_repuestos::Entity",
        from = "Column::RepuestoId",
        to = "super::activos_repuestos::Column::IdRepuesto",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ActivosRepuestos,
    #[sea_orm(
        belongs_to = "super::compras_cotizaciones::Entity",
        from = "Column::CotizacionId",
        to = "super::compras_cotizaciones::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ComprasCotizaciones,
}

impl Related<super::activos_repuestos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivosRepuestos.def()
    }
}

impl Related<super::compras_cotizaciones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComprasCotizaciones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
