//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config_empresa")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub logo: Option<String>,
    pub nombre_comercial: String,
    pub razon_social: String,
    pub ruc: String,
    pub dv: String,
    pub telefono: String,
    pub correo: String,
    #[sea_orm(column_type = "Text")]
    pub direccion: String,
    pub ciudad: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
