//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rol_permisos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_rol_permiso: i32,
    pub rol_id: i32,
    pub permiso_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::permisos::Entity",
        from = "Column::PermisoId",
        to = "super::permisos::Column::IdPermiso",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Permisos,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RolId",
        to = "super::roles::Column::IdRol",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Roles,
}

impl Related<super::permisos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permisos.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
